version: '3.8'

services:
  # Spring Boot 后端
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: image-recognition-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker-remote
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-imagerecognition2024}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis2024}
      DOUBAO_API_KEY: ${DOUBAO_API_KEY:-api-key-20250929130415}
      JWT_SECRET: ${JWT_SECRET:-mySecretKey123456789}
      VOLCENGINE_ACCESS_KEY_ID: ${VOLCENGINE_ACCESS_KEY_ID:-}
      VOLCENGINE_SECRET_ACCESS_KEY: ${VOLCENGINE_SECRET_ACCESS_KEY:-}
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
    volumes:
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
    networks:
      - image-recognition-network
    # 移除数据库依赖，使用远程数据库
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/doubao/image/status"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

  # Vue.js 前端
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: image-recognition-frontend
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"
    volumes:
      - frontend_logs:/var/log/nginx
    networks:
      - image-recognition-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      timeout: 10s
      retries: 3
      interval: 30s
      start_period: 30s

networks:
  image-recognition-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  backend_logs:
    driver: local
  backend_uploads:
    driver: local
  frontend_logs:
    driver: local
